create or replace 
TYPE AMB_ERROR AS OBJECT(
  error_message varchar2(4000),
  CONSTRUCTOR FUNCTION AMB_ERROR(f_msg varchar2 default NULL) RETURN SELF AS RESULT,
  STATIC FUNCTION EMPTY_ERROR return AMB_ERROR,
  MEMBER FUNCTION IS_EMPTY return BOOLEAN,
  MEMBER FUNCTION GET_MESSAGE return varchar2
);
